main: main.o unindent.o indent.o
	g++ -o main main.o unindent.o indent.o 

test: test.o unindent.o indent.o
	g++ -o test test.o unindent.o indent.o

test.o: test.cpp 

main.o: main.cpp unindent.h indent.h

unindent.o: unindent.cpp unindent.h

indent.o: indent.cpp indent.h

clean: 
	rm -f main.o unindent.o indent.o test.o